language: swift
os: osx
osx_image: xcode10
xcode_project: SExtensions.xcodeproj
xcode_scheme: SExtensions
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS MAX
before_install:
  - gem install bundle
  - bundle install
  - brew update
  - brew install swiftformat
before_script:
  - bundle exec danger
matrix:
  include:
    - osx_image: xcode10
      env: iPhone XS MAX
    - osx_image: xcode10
      env: iPad Pro (11-inch)
after_success:
  - bash <(curl -s https://codecov.io/bash)