language: swift
os: osx
osx_image: xcode10
xcode_project: SExtensions.xcodeproj
xcode_scheme: SExtensions
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPad Pro (9.7-inch)
before_install:
  - bundle install
before_script:
  - gem install bundle
  - if [ $DANGER == "ALLOW" ]; then
      bundle exec danger;
    fi
matrix:
  include:
    - osx_image: xcode10
      env: CI_BUILD_TARGET='nap' CI_DEVICE='iPhone X (12.0)' DANGER="ALLOW"
    - osx_image: xcode10
      env: CI_BUILD_TARGET='nap' CI_DEVICE='iPad Pro (9.7-inch)'