language: swift
os: osx
osx_image: xcode10
xcode_project: SExtensions.xcodeproj
xcode_scheme: SExtensions
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPad Pro (9.7-inch)
before_install:
  - bundle install
before_script:
  - gem install bundle
matrix:
  include:
    - osx_image: xcode10
      env: iPhone XS MAX (12.0)
    - osx_image: xcode10
      env: iPad Pro (11-inch)